package Dto;
// Generated 11/04/2020 06:09:23 PM by Hibernate Tools 4.3.1



/**
 * Bodega generated by hbm2java
 */
public class Bodega  implements java.io.Serializable {


     private Integer idBodega;
     private Estante estante;
     private String nombre;

    public Bodega() {
    }

    public Bodega(Estante estante, String nombre) {
       this.estante = estante;
       this.nombre = nombre;
    }
   
    public Integer getIdBodega() {
        return this.idBodega;
    }
    
    public void setIdBodega(Integer idBodega) {
        this.idBodega = idBodega;
    }
    public Estante getEstante() {
        return this.estante;
    }
    
    public void setEstante(Estante estante) {
        this.estante = estante;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


