package Dto;
// Generated 11/04/2020 06:09:23 PM by Hibernate Tools 4.3.1



/**
 * DetalleFactura generated by hbm2java
 */
public class DetalleFactura  implements java.io.Serializable {


     private Integer idDetalleFactura;
     private Factura factura;
     private Insumos insumos;
     private Productos productos;
     private int valorVenta;
     private int cantidadVenta;
     private int cantidadEntrante;
     private String unidadRegistrada;

    public DetalleFactura() {
    }

	
    public DetalleFactura(Factura factura, int valorVenta, int cantidadVenta, int cantidadEntrante, String unidadRegistrada) {
        this.factura = factura;
        this.valorVenta = valorVenta;
        this.cantidadVenta = cantidadVenta;
        this.cantidadEntrante = cantidadEntrante;
        this.unidadRegistrada = unidadRegistrada;
    }
    public DetalleFactura(Factura factura, Insumos insumos, Productos productos, int valorVenta, int cantidadVenta, int cantidadEntrante, String unidadRegistrada) {
       this.factura = factura;
       this.insumos = insumos;
       this.productos = productos;
       this.valorVenta = valorVenta;
       this.cantidadVenta = cantidadVenta;
       this.cantidadEntrante = cantidadEntrante;
       this.unidadRegistrada = unidadRegistrada;
    }
   
    public Integer getIdDetalleFactura() {
        return this.idDetalleFactura;
    }
    
    public void setIdDetalleFactura(Integer idDetalleFactura) {
        this.idDetalleFactura = idDetalleFactura;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Insumos getInsumos() {
        return this.insumos;
    }
    
    public void setInsumos(Insumos insumos) {
        this.insumos = insumos;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public int getValorVenta() {
        return this.valorVenta;
    }
    
    public void setValorVenta(int valorVenta) {
        this.valorVenta = valorVenta;
    }
    public int getCantidadVenta() {
        return this.cantidadVenta;
    }
    
    public void setCantidadVenta(int cantidadVenta) {
        this.cantidadVenta = cantidadVenta;
    }
    public int getCantidadEntrante() {
        return this.cantidadEntrante;
    }
    
    public void setCantidadEntrante(int cantidadEntrante) {
        this.cantidadEntrante = cantidadEntrante;
    }
    public String getUnidadRegistrada() {
        return this.unidadRegistrada;
    }
    
    public void setUnidadRegistrada(String unidadRegistrada) {
        this.unidadRegistrada = unidadRegistrada;
    }




}


