package Dto;
// Generated 11/04/2020 06:09:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Insumos generated by hbm2java
 */
public class Insumos  implements java.io.Serializable {


     private Integer idInsumos;
     private String nombre;
     private int cantidad;
     private int precio;
     private String descripcion;
     private Date fecha;
     private Set detalleFacturas = new HashSet(0);
     private Set registroSalidas = new HashSet(0);

    public Insumos() {
    }

	
    public Insumos(String nombre, int cantidad, int precio, String descripcion, Date fecha) {
        this.nombre = nombre;
        this.cantidad = cantidad;
        this.precio = precio;
        this.descripcion = descripcion;
        this.fecha = fecha;
    }
    public Insumos(String nombre, int cantidad, int precio, String descripcion, Date fecha, Set detalleFacturas, Set registroSalidas) {
       this.nombre = nombre;
       this.cantidad = cantidad;
       this.precio = precio;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.detalleFacturas = detalleFacturas;
       this.registroSalidas = registroSalidas;
    }
   
    public Integer getIdInsumos() {
        return this.idInsumos;
    }
    
    public void setIdInsumos(Integer idInsumos) {
        this.idInsumos = idInsumos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }
    public Set getRegistroSalidas() {
        return this.registroSalidas;
    }
    
    public void setRegistroSalidas(Set registroSalidas) {
        this.registroSalidas = registroSalidas;
    }




}


