package Dto;
// Generated 11/04/2020 06:09:23 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer idProductos;
     private Estante estante;
     private String descripcion;
     private int idTipoProducto;
     private byte[] foto;
     private int cantidadExistente;
     private String nombre;
     private int precioUnidad;
     private int precioLibra;
     private int precioKilo;
     private int precioArroba;
     private int precioBulto;
     private TipoProducto tipoProducto;
     private Set detalleFacturas = new HashSet(0);

    public Productos() {
    }

	
    public Productos(Estante estante, String descripcion, int idTipoProducto, byte[] foto, int cantidadExistente, String nombre, int precioUnidad, int precioLibra, int precioKilo, int precioArroba, int precioBulto) {
        this.estante = estante;
        this.descripcion = descripcion;
        this.idTipoProducto = idTipoProducto;
        this.foto = foto;
        this.cantidadExistente = cantidadExistente;
        this.nombre = nombre;
        this.precioUnidad = precioUnidad;
        this.precioLibra = precioLibra;
        this.precioKilo = precioKilo;
        this.precioArroba = precioArroba;
        this.precioBulto = precioBulto;
    }
    public Productos(Estante estante, String descripcion, int idTipoProducto, byte[] foto, int cantidadExistente, String nombre, int precioUnidad, int precioLibra, int precioKilo, int precioArroba, int precioBulto, TipoProducto tipoProducto, Set detalleFacturas) {
       this.estante = estante;
       this.descripcion = descripcion;
       this.idTipoProducto = idTipoProducto;
       this.foto = foto;
       this.cantidadExistente = cantidadExistente;
       this.nombre = nombre;
       this.precioUnidad = precioUnidad;
       this.precioLibra = precioLibra;
       this.precioKilo = precioKilo;
       this.precioArroba = precioArroba;
       this.precioBulto = precioBulto;
       this.tipoProducto = tipoProducto;
       this.detalleFacturas = detalleFacturas;
    }
   
    public Integer getIdProductos() {
        return this.idProductos;
    }
    
    public void setIdProductos(Integer idProductos) {
        this.idProductos = idProductos;
    }
    public Estante getEstante() {
        return this.estante;
    }
    
    public void setEstante(Estante estante) {
        this.estante = estante;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getIdTipoProducto() {
        return this.idTipoProducto;
    }
    
    public void setIdTipoProducto(int idTipoProducto) {
        this.idTipoProducto = idTipoProducto;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public int getCantidadExistente() {
        return this.cantidadExistente;
    }
    
    public void setCantidadExistente(int cantidadExistente) {
        this.cantidadExistente = cantidadExistente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getPrecioUnidad() {
        return this.precioUnidad;
    }
    
    public void setPrecioUnidad(int precioUnidad) {
        this.precioUnidad = precioUnidad;
    }
    public int getPrecioLibra() {
        return this.precioLibra;
    }
    
    public void setPrecioLibra(int precioLibra) {
        this.precioLibra = precioLibra;
    }
    public int getPrecioKilo() {
        return this.precioKilo;
    }
    
    public void setPrecioKilo(int precioKilo) {
        this.precioKilo = precioKilo;
    }
    public int getPrecioArroba() {
        return this.precioArroba;
    }
    
    public void setPrecioArroba(int precioArroba) {
        this.precioArroba = precioArroba;
    }
    public int getPrecioBulto() {
        return this.precioBulto;
    }
    
    public void setPrecioBulto(int precioBulto) {
        this.precioBulto = precioBulto;
    }
    public TipoProducto getTipoProducto() {
        return this.tipoProducto;
    }
    
    public void setTipoProducto(TipoProducto tipoProducto) {
        this.tipoProducto = tipoProducto;
    }
    public Set getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }




}


