package Dto;
// Generated 11/04/2020 06:09:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Produccion generated by hbm2java
 */
public class Produccion  implements java.io.Serializable {


     private Integer idProduccion;
     private String nombre;
     private Date fecha;
     private String tipo;
     private int cantidadEntrante;
     private String unidadMedida;
     private Set tipoProductos = new HashSet(0);

    public Produccion() {
    }

	
    public Produccion(String nombre, Date fecha, String tipo, int cantidadEntrante, String unidadMedida) {
        this.nombre = nombre;
        this.fecha = fecha;
        this.tipo = tipo;
        this.cantidadEntrante = cantidadEntrante;
        this.unidadMedida = unidadMedida;
    }
    public Produccion(String nombre, Date fecha, String tipo, int cantidadEntrante, String unidadMedida, Set tipoProductos) {
       this.nombre = nombre;
       this.fecha = fecha;
       this.tipo = tipo;
       this.cantidadEntrante = cantidadEntrante;
       this.unidadMedida = unidadMedida;
       this.tipoProductos = tipoProductos;
    }
   
    public Integer getIdProduccion() {
        return this.idProduccion;
    }
    
    public void setIdProduccion(Integer idProduccion) {
        this.idProduccion = idProduccion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public int getCantidadEntrante() {
        return this.cantidadEntrante;
    }
    
    public void setCantidadEntrante(int cantidadEntrante) {
        this.cantidadEntrante = cantidadEntrante;
    }
    public String getUnidadMedida() {
        return this.unidadMedida;
    }
    
    public void setUnidadMedida(String unidadMedida) {
        this.unidadMedida = unidadMedida;
    }
    public Set getTipoProductos() {
        return this.tipoProductos;
    }
    
    public void setTipoProductos(Set tipoProductos) {
        this.tipoProductos = tipoProductos;
    }




}


